//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class profile {
    
    private string steamID64Field;
    
    private string steamIDField;
    
    private string onlineStateField;
    
    private string stateMessageField;
    
    private string privacyStateField;
    
    private string visibilityStateField;
    
    private string avatarIconField;
    
    private string avatarMediumField;
    
    private string avatarFullField;
    
    private string vacBannedField;
    
    private string tradeBanStateField;
    
    private string isLimitedAccountField;
    
    private string customURLField;
    
    private string memberSinceField;
    
    private string steamRatingField;
    
    private string hoursPlayed2WkField;
    
    private string headlineField;
    
    private string locationField;
    
    private string realnameField;
    
    private string summaryField;
    
    private profileMostPlayedGamesMostPlayedGame[][] mostPlayedGamesField;
    
    private profileGroupsGroup[][] groupsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string steamID64 {
        get {
            return this.steamID64Field;
        }
        set {
            this.steamID64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string steamID {
        get {
            return this.steamIDField;
        }
        set {
            this.steamIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string onlineState {
        get {
            return this.onlineStateField;
        }
        set {
            this.onlineStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stateMessage {
        get {
            return this.stateMessageField;
        }
        set {
            this.stateMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string privacyState {
        get {
            return this.privacyStateField;
        }
        set {
            this.privacyStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string visibilityState {
        get {
            return this.visibilityStateField;
        }
        set {
            this.visibilityStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarIcon {
        get {
            return this.avatarIconField;
        }
        set {
            this.avatarIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarMedium {
        get {
            return this.avatarMediumField;
        }
        set {
            this.avatarMediumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarFull {
        get {
            return this.avatarFullField;
        }
        set {
            this.avatarFullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string vacBanned {
        get {
            return this.vacBannedField;
        }
        set {
            this.vacBannedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tradeBanState {
        get {
            return this.tradeBanStateField;
        }
        set {
            this.tradeBanStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isLimitedAccount {
        get {
            return this.isLimitedAccountField;
        }
        set {
            this.isLimitedAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customURL {
        get {
            return this.customURLField;
        }
        set {
            this.customURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string memberSince {
        get {
            return this.memberSinceField;
        }
        set {
            this.memberSinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string steamRating {
        get {
            return this.steamRatingField;
        }
        set {
            this.steamRatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hoursPlayed2Wk {
        get {
            return this.hoursPlayed2WkField;
        }
        set {
            this.hoursPlayed2WkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string headline {
        get {
            return this.headlineField;
        }
        set {
            this.headlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string realname {
        get {
            return this.realnameField;
        }
        set {
            this.realnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("mostPlayedGame", typeof(profileMostPlayedGamesMostPlayedGame), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public profileMostPlayedGamesMostPlayedGame[][] mostPlayedGames {
        get {
            return this.mostPlayedGamesField;
        }
        set {
            this.mostPlayedGamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("group", typeof(profileGroupsGroup), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public profileGroupsGroup[][] groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class profileMostPlayedGamesMostPlayedGame {
    
    private string gameNameField;
    
    private string gameLinkField;
    
    private string gameIconField;
    
    private string gameLogoField;
    
    private string gameLogoSmallField;
    
    private string hoursPlayedField;
    
    private string hoursOnRecordField;
    
    private string statsNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gameName {
        get {
            return this.gameNameField;
        }
        set {
            this.gameNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gameLink {
        get {
            return this.gameLinkField;
        }
        set {
            this.gameLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gameIcon {
        get {
            return this.gameIconField;
        }
        set {
            this.gameIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gameLogo {
        get {
            return this.gameLogoField;
        }
        set {
            this.gameLogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gameLogoSmall {
        get {
            return this.gameLogoSmallField;
        }
        set {
            this.gameLogoSmallField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hoursPlayed {
        get {
            return this.hoursPlayedField;
        }
        set {
            this.hoursPlayedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hoursOnRecord {
        get {
            return this.hoursOnRecordField;
        }
        set {
            this.hoursOnRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string statsName {
        get {
            return this.statsNameField;
        }
        set {
            this.statsNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class profileGroupsGroup {
    
    private string groupID64Field;
    
    private string groupNameField;
    
    private string groupURLField;
    
    private string headlineField;
    
    private string summaryField;
    
    private string avatarIconField;
    
    private string avatarMediumField;
    
    private string avatarFullField;
    
    private string memberCountField;
    
    private string membersInChatField;
    
    private string membersInGameField;
    
    private string membersOnlineField;
    
    private string isPrimaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string groupID64 {
        get {
            return this.groupID64Field;
        }
        set {
            this.groupID64Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string groupName {
        get {
            return this.groupNameField;
        }
        set {
            this.groupNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string groupURL {
        get {
            return this.groupURLField;
        }
        set {
            this.groupURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string headline {
        get {
            return this.headlineField;
        }
        set {
            this.headlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarIcon {
        get {
            return this.avatarIconField;
        }
        set {
            this.avatarIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarMedium {
        get {
            return this.avatarMediumField;
        }
        set {
            this.avatarMediumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avatarFull {
        get {
            return this.avatarFullField;
        }
        set {
            this.avatarFullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string memberCount {
        get {
            return this.memberCountField;
        }
        set {
            this.memberCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string membersInChat {
        get {
            return this.membersInChatField;
        }
        set {
            this.membersInChatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string membersInGame {
        get {
            return this.membersInGameField;
        }
        set {
            this.membersInGameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string membersOnline {
        get {
            return this.membersOnlineField;
        }
        set {
            this.membersOnlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isPrimary {
        get {
            return this.isPrimaryField;
        }
        set {
            this.isPrimaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private profile[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("profile")]
    public profile[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
